### ISSUE TITLE
XML error

### ISSUE THREAD

**Issue by Hellomik2002** [PeculiarVentures/xmldsigjs#46]
I installed webcrypto with npm by but still have issue when I try new XmlDSigJs.SignedXml().Sign(...)
```
XmlError {
  prefix: 'XMLJS',
  code: 14,
  name: 'XmlError',
  message: 'XMLJS0014: WebCrypto module is not found',
  stack: 'Error: XMLJS0014: WebCrypto module is not found\n' +
    '    at new XmlError (C:\\projects\\notr\\node_modules\\xml-core\\dist\\index.js:216:22)\n' +
    '    at Function.get crypto [as crypto] (C:\\projects\\notr\\node_modules\\xmldsigjs\\build\\index.js:22:19)\n' +
    '    at RsaKeyValue.importKey (C:\\projects\\notr\\node_modules\\xmldsigjs\\build\\index.js:1539:39)\n' +
    '    at KeyValue.importKey (C:\\projects\\notr\\node_modules\\xmldsigjs\\build\\index.js:1710:34)\n' +
    '    at SignedXml.ApplySignOptions (C:\\projects\\notr\\node_modules\\xmldsigjs\\build\\index.js:2656:28)\n' +
    '    at SignedXml.Sign (C:\\projects\\notr\\node_modules\\xmldsigjs\\build\\index.js:2360:20)\n' +
    '    at C:\\projects\\notr\\cryptXML.js:59:22'
}
```

**Comment by colourful-land** [comment]
You might have felt into the same trap I did a while ago. First, if you do `npm install webcrypto` it doesn't provide WebCrypto interface. The 3 libraries that do are (listed in this post by me)[https://community.tokenscript.org/t/the-confusing-current-status-of-various-node-js-webcrypto-api-providers/393] and I think the only one that works with xmldsigjs is webcrypto-ossl. (That post has now other libraries failed to work with xmldsigjs.) Even worse, these libraries have different initialisation methods so one can't serve as the drop-in replacement of another without tweak.
